# Set prefix from Ctrl-b to Ctrl-s
set -g prefix C-s    # set prefix to C-s
unbind C-b
bind C-s send-prefix # send (C-s) x 2 to others apps

# Toggle status
set -g status off
bind q set-option status

# status bar theme 
set -g status-style bg=default
set -g message-style bg=default
set -g status-right ""
set-option -g status-position top

# Source tmux.conf Prefix+r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Copy mode + vi : Prefix+[
set -g status-keys vi # prefix + :
set-window-option -g mode-keys vi # prefix + [
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy" # Use xclip for Linux

# Plugins 
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# impt for plugins always on last line
run '~/.tmux/plugins/tpm/tpm'
