# Set prefix from Ctrl-b to Ctrl-s
set -g prefix C-s
unbind C-b
bind C-s send-prefix
bind r source-file ~/.tmux.conf \; display "Reloaded!"

set -g status on          # Toggle status
#set -g status off         # hide status bar
bind q set-option status  # toggle 

# status bar theme 
set -g status-style bg=default
set -g message-style bg=default
set -g status-right ""
set-option -g status-position top

# Copy mode + vi : Prefix+[
set -g status-keys vi # prefix + :
set-window-option -g mode-keys vi # prefix + [

# prefix+[ enter copy mode
# v to select 
# y to yank
# prefix+] paste 

set -s copy-command 'wl-copy'
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
