term xterm-256color
font_family      Iosevka Nerd Font
font_size 16.0
cursor_shape block
shell_integration no-cursor
background_opacity         1
disable_ligatures always
confirm_os_window_close 0

# Base16 Black Metal (Gorgoroth) - kitty color config
# Scheme by metalelf0 (https://github.com/metalelf0)
#background            #141415
background            #000000
cursor                #fcee0b
foreground            #ddeedd
selection_foreground  #ffffff
selection_background  #4d4d4d
url_color #999999
active_border_color #333333
inactive_border_color #121212
active_tab_background #000000
active_tab_foreground #c1c1c1
inactive_tab_background #121212
inactive_tab_foreground #999999
tab_bar_background #121212

# normal
color0 #000000
color1 #5f8787
color2 #9b8d7f
color3 #8c7f70
# folder color
color4 #936c7a 
color5 #999999
color6 #aaaaaa
color7 #c1c1c1

# bright
color8 #333333
color9 #5f8787
color10 #9b8d7f
color11 #8c7f70
color12 #888888
color13 #999999
color14 #aaaaaa
color15 #c1c1c1

# extended base16 colors
color16 #aaaaaa
color17 #444444
color18 #121212
color19 #222222
color20 #999999
color21 #999999
