term xterm-256color
font_family      Fira Code
#font_family      MxPlus ToshibaTxL1 8x16
font_size 18.0
cursor_shape block
shell_integration no-cursor
background_opacity         1
disable_ligatures always
confirm_os_window_close 0

background            #000000
cursor                #dedede
foreground            #ddeedd
include dark-theme.auto.conf
