term xterm-256color
font_family      Iosevka Nerd Font
font_size 15.0
cursor_shape block
shell_integration no-cursor
background_opacity         0.95
disable_ligatures always
confirm_os_window_close 0

include base16.conf
